# Generated by Django 5.1 on 2024-09-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManuAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(max_length=2000)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_no', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ManuBsn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(max_length=2000)),
                ('bsn_name', models.CharField(max_length=200)),
                ('reg_no', models.CharField(max_length=50)),
                ('ceo_name', models.CharField(max_length=50)),
            ],
        ),
    ]
