# Generated by Django 5.1 on 2024-09-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('image_url', models.URLField(max_length=2000)),
                ('product_type', models.CharField(max_length=200)),
            ],
        ),
    ]
